### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by VkyVignesh** [Sriharia/SHAREthem#3]
Hi Sri,

I have installed and tested your application from play store. it was crashing . Then i downloaded a code and found an Exception while debugging. Actually you are checking isShareThemSSID() with detected networks. In that, you are splitting ssid by **"-"**. My wifi name is **"harry-wifi"** . In  isShareThemSSID(), it's spits ["harry", "wifi"] and tries to decode it. there it's  giving an exception.

**Existing logic:**
public static boolean isShareThemSSID(String ssid) {
        String[] splits = ssid.split("-");
        if (splits.length != 2)
            return false;
        **String[] names = new String(Base64.decode(splits[1], Base64.DEFAULT)).split("\\|");**
        return names.length == 3 && names[1].equals(SENDER_WIFI_NAMING_SALT);
    }

**Consider the change **
public static boolean isShareThemSSID(String ssid) {
        String[] splits = ssid.split("-");
        if (splits.length != 2)
            return false;
        **try {
            String[] names = new String(Base64.decode(splits[1], Base64.DEFAULT)).split("\\|");
            return names.length == 3 && names[1].equals(SENDER_WIFI_NAMING_SALT);
        }  catch (Exception e) {
         return false;
        }**
   }

This will avoid crashing in your application.

**Comment by Sriharia** [comment]
thanks for the pointing it out. fixed it

**Comment by anitaa1990** [comment]
Not sure if this is related to the same issue above. But I downloaded app from PlayStore and it is crashing when clicking on Receive button. 

This is the exception:

```
FATAL EXCEPTION: main
                                                   Process: com.tml.sharethem.demo, PID: 30231
                                                   java.lang.RuntimeException: Error receiving broadcast Intent { act=android.net.wifi.SCAN_RESULTS flg=0x4000010 (has extras) } in com.tml.sharethem.receiver.ReceiverActivity$WifiScanner@a65d9be
                                                       at android.app.LoadedApk$ReceiverDispatcher$Args.run(LoadedApk.java:1132)
                                                       at android.os.Handler.handleCallback(Handler.java:751)
                                                       at android.os.Handler.dispatchMessage(Handler.java:95)
                                                       at android.os.Looper.loop(Looper.java:154)
                                                       at android.app.ActivityThread.main(ActivityThread.java:6123)
                                                       at java.lang.reflect.Method.invoke(Native Method)
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:867)
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:757)
                                                    Caused by: java.lang.IllegalArgumentException: bad base-64
                                                       at android.util.Base64.decode(Base64.java:161)
                                                       at android.util.Base64.decode(Base64.java:136)
                                                       at android.util.Base64.decode(Base64.java:118)
                                                       at com.tml.sharethem.utils.WifiUtils.isShareThemSSID(WifiUtils.java:215)
                                                       at com.tml.sharethem.receiver.ReceiverActivity$WifiScanner.onReceive(ReceiverActivity.java:446)
                                                       at android.app.LoadedApk$ReceiverDispatcher$Args.run(LoadedApk.java:1122)
                                                       at android.os.Handler.handleCallback(Handler.java:751) 
                                                       at android.os.Handler.dispatchMessage(Handler.java:95) 
                                                       at android.os.Looper.loop(Looper.java:154) 
                                                       at android.app.ActivityThread.main(ActivityThread.java:6123) 
                                                       at java.lang.reflect.Method.invoke(Native Method)
```
